def print_squares(n):
    pass


print('Testcase 1: print_squares(3)')
print('-' * 10)
print('Expected:')
print('***')
print('* *')
print('***')
print('Actual:')
print_squares(3)

print('\nTestcase 2: print_squares(7)')
print('-' * 10)
print('Expected:')
print('*******')
print('*     *')
print('* *** *')
print('* * * *')
print('* *** *')
print('*     *')
print('*******')
print('Actual:')
print_squares(7)

print('\nTestcase 3: print_squares(11)')
print('-' * 10)
print('Expected:')
print('***********')
print('*         *')
print('* ******* *')
print('* *     * *')
print('* * *** * *')
print('* * * * * *')
print('* * *** * *')
print('* *     * *')
print('* ******* *')
print('*         *')
print('***********')
print('Actual:')
print_squares(11)
